# fly.toml app configuration file generated for voxon on 2026-06-09T15:17:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voxon'
primary_region = 'fra'
kill_signal = 'SIGTERM'
kill_timeout = 300 # Gives voxon 5 minutes to gracefully drain WebSocket connections on redeployment

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4000"
  PHX_HOST = 'voxon.fly.dev'
  PHX_SERVER = "true"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "connections" # Track total active, stateful WebSockets instead of HTTP requests
    hard_limit = 15000
    soft_limit = 10000

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
